name: social
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^4.5.4
  firebase_messaging: ^7.0.1
  firebase_auth: ^0.18.1
  image_picker: ^0.6.7+11
  firebase_storage: ^4.0.1
  cloud_firestore: ^0.14.1+3
  firebase_core: ^0.5.0+1
  flutter_svg: ^0.19.1
  cached_network_image: ^2.3.3
  image: ^2.1.18
  geolocator: ^6.1.4
  animator: ^2.0.1
  timeago: ^2.0.28
  cloud_functions: ^0.7.0+1
  agora_rtc_engine: ^3.1.3
  permission_handler: ^5.0.1
  stripe_payment: ^1.0.6
  modal_progress_hud: ^0.1.3
  intl: ^0.16.1
  webview_flutter: ^1.0.7
  http_auth: ^0.3.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logoLauncher.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logoLauncher.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Medium.ttf
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 700
  assets:
    - assets/images/google_signin_button.png
    - assets/images/upload.svg
    - assets/images/search.svg
    - assets/images/activity_feed.svg
    - assets/images/no_content.jpg
    - assets/images/logo.png
    - assets/images/logoLauncher.png
    - assets/images/coin.png
